### ISSUE TITLE
[TC-408] Documentation for creating ssl keys is missing a field.

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#1001]
<p>The documentation to generate ssl keys is missing the delivery service field. generating keys with that field being null will cause issues on Riak.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
POST /api/1.2/deliveryservices/sslkeys/generate

Generates SSL crt, csr, and <span class="code-keyword">private</span> key <span class="code-keyword">for</span> a delivery service

Authentication Required: Yes

Role(s) Required: Admin

Request Properties

Parameter	Type	Description
key	string	xml_id of the delivery service
version	string	version of the keys being generated
hostname	string	the pristine hostname of the delivery service
country	string	 
state	string	 
city	string	 
org	string	 
unit	<span class="code-object">boolean</span>	 
Request Example

{
  <span class="code-quote">"key"</span>: <span class="code-quote">"ds-01"</span>,
  <span class="code-quote">"businessUnit"</span>: <span class="code-quote">"CDN Engineering"</span>,
  <span class="code-quote">"version"</span>: <span class="code-quote">"3"</span>,
  <span class="code-quote">"hostname"</span>: <span class="code-quote">"tr.ds-01.ott.kabletown.com"</span>,
  <span class="code-quote">"certificate"</span>: {
    <span class="code-quote">"key"</span>: <span class="code-quote">"some_key"</span>,
    <span class="code-quote">"csr"</span>: <span class="code-quote">"some_csr"</span>,
    <span class="code-quote">"crt"</span>: <span class="code-quote">"some_crt"</span>
  },
  <span class="code-quote">"country"</span>: <span class="code-quote">"US"</span>,
  <span class="code-quote">"organization"</span>: <span class="code-quote">"Kabletown"</span>,
  <span class="code-quote">"city"</span>: <span class="code-quote">"Denver"</span>,
  <span class="code-quote">"state"</span>: <span class="code-quote">"Colorado"</span>
}</pre>
</div></div>

<p>These are the fields required. Notice the delivery service is null. </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
{
    <span class="code-quote">"cdn"</span>: <span class="code-keyword">null</span>,
    <span class="code-quote">"certificate"</span>: {
        <span class="code-quote">"crt"</span>: 
        <span class="code-quote">"csr"</span>:         <span class="code-quote">"key"</span>:     },
    <span class="code-quote">"city"</span>: <span class="code-quote">"Denver"</span>,
    <span class="code-quote">"country"</span>: <span class="code-quote">"US"</span>,
    <span class="code-quote">"deliveryservice"</span>: <span class="code-keyword">null</span>,
    <span class="code-quote">"hostname"</span>: <span class="code-quote">"*.linear-chi-pil-red.xcr.comcast.net"</span>,
    <span class="code-quote">"key"</span>: <span class="code-quote">"linear-chi-pil-red"</span>,
    <span class="code-quote">"org"</span>: <span class="code-keyword">null</span>,
    <span class="code-quote">"state"</span>: <span class="code-quote">"Colorado"</span>,
    <span class="code-quote">"unit"</span>: <span class="code-quote">"IPCDN"</span>,
    <span class="code-quote">"version"</span>: <span class="code-quote">"1"</span>
}</pre>
</div></div>

Author: Joseph Pappano
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-408">https://issues.apache.org/jira/browse/TC-408</a>
Found Version: 2.1.0

**Comment by hbeatty** [comment]
This needs to be backported to 2.1.
