### ISSUE TITLE
[TC-209] Experimental Traffic Monitor polling OFFLINE caches

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#1014]
<p>The experimental (golang) version of Traffic Monitor appears to be polling <tt>OFFLINE</tt> caches.</p>

Author: Jeff Elsloo
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-209">https://issues.apache.org/jira/browse/TC-209</a>
Found Version: 2.1.0

**Comment by rob05c** [comment]
Fixed in 454ce67
