### ISSUE TITLE
[TC-425] TPv2 - add the ability to manage federations

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#1056]
<p>In order to achieve feature parity with the existing TO UI, TPv2 must support the management of Federations. </p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-425">https://issues.apache.org/jira/browse/TC-425</a>

**Comment by mitchell852** [comment]
duplicate
