### ISSUE TITLE
[TC-396] Show version chooser on TC docs page

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#1063]
<p>Traffic Control will likely need to host documentation for multiple versions simultaneously. </p>

<p>It would be nice to have a version chooser to select which version docs you wanted to view</p>

Author: Eric Friedrich
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-396">https://issues.apache.org/jira/browse/TC-396</a>

**Comment by hbeatty** [comment]
This has been completed with moving to http://traffic-control-cdn.readthedocs.io/en/latest/
