### ISSUE TITLE
[TC-518] ToCDUCheck and ToCHRCheck: Value formatted as float instead of int

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#1090]
<p>CDU check return value are formatted as a float while the database values were stored as int (mysql) and bigint (postgresql).</p>

<p>This check fails against 2.0+</p>

Author: Steve Malenfant
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-518">https://issues.apache.org/jira/browse/TC-518</a>
Found Version: 2.1.0

**Comment by hbeatty** [comment]
In Jira this was assigned to @smalenfant

**Comment by hbeatty** [comment]
@smalenfant #804 has been merged to master. Can you create a backport PR for the 2.1.x branch?
