### ISSUE TITLE
[TC-539] ability to select all when filtering to add DSes to user

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#1091]
<p>when using filters to assign delivery services to users, you are unable to select all.</p>

Author: Sean Aoyagi
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-539">https://issues.apache.org/jira/browse/TC-539</a>
Found Version: 2.0.0

**Comment by mitchell852** [comment]
tenancy will soon be in place thus eliminating the need to assign individual delivery services to a user.
