### ISSUE TITLE
Traffic Ops Client Doesn't Refresh Cookie

### ISSUE THREAD

**Issue by rob05c** [apache/incubator-trafficcontrol#1133]
Currently, the `traffic_ops/client` never independently pings TO, or otherwise refreshes the cookie. This means if a client logs in, and then doesn't make a request for 24 hours, that client `Session` is permanently broken.

The client should ping Traffic Ops and refresh the cookie at some interval less than the cookie expiration (e.g. `min(max(expiration/8, 1hr), expiration/2)`).

**Comment by mitchell852** [comment]
@rob05c - can you put a severity level label on this? trivial, minor, major, critical...

**Comment by rob05c** [comment]
Fixed by #1547
