### ISSUE TITLE
Traffic Ops Client Should Get a New Cookie on Login Fail

### ISSUE THREAD

**Issue by rob05c** [apache/incubator-trafficcontrol#1134]
Currently, if the Traffic Ops Client encounters a login failure, for example if the cookie expires or the server's secret is changed, that client `Session` is permanently broken.

If any Traffic Ops request returns a 401, the Client should try to log in again, rather than just permanently failing, and requiring users of the client to all implement the same duplicate client recreation on error logic.

**Comment by mitchell852** [comment]
@rob05c - can you put a severity level label on this? trivial, minor, major, critical...

**Comment by rob05c** [comment]
Fixed by #1547
