### ISSUE TITLE
Traffic Server administration docs are out of date

### ISSUE THREAD

**Issue by dneuman64** [apache/incubator-trafficcontrol#1135]
The [Administrator's Guide -> Traffic Server administration](https://trafficcontrol.incubator.apache.org/docs/latest/admin/traffic_server.html#traffic-server-administration) docs are extrememly out of date.  They reference links to 1.6 and 1.7 versions of traffic control and 5.3.x versions of ATS.  These docs should be updated so that either the versions are recent or we provide links that are version agnostic (master).

**Comment by ashish-timilsina** [comment]
#1834

**Comment by dneuman64** [comment]
This is closed by #1834
