### ISSUE TITLE
Steering Race Condition

### ISSUE THREAD

**Issue by elsloo** [apache/incubator-trafficcontrol#1145]
A race condition exists with steering, where the steering configuration will not work if it is created using new delivery services that have yet to be snapshotted to propagate down to Traffic Router. This is because the steering watcher tries to locate the delivery service when it sees the new steering configuration, however, it is unable to locate the delivery service because the config has not yet been snapshotted. The issue persists after a snapshot, because the steering configuration remains the same. The only way to fix the issue is the change the weighting or order, or some other steering configuration, which causes a "diff" to appear in the JSON, which triggers a process in Traffic Router to try to reconfigure all steering assignments. By this point the config has been snapshotted and the process does find the subordinate delivery services. Keep in mind that we have steering and client steering, both affected by this.

There are a couple ways to correct this issue, but due to the asynchronous nature of how the steering watcher is implemented, we need to ensure that the current config does not get dropped on the floor when the config is processed, which would cause any in-flight steering requests to fail. Instead, the config should be processed "on the side" and swapped in when complete, similar to how we do things for other configs. Other approaches are valid too; whatever works as long as we can continue to handle steering requests while the config is processed.

**Comment by mitchell852** [comment]
@elsloo  - can you put a severity level label on this? trivial, minor, major, critical...

**Comment by elsloo** [comment]
This was resolved via #1843.
