### ISSUE TITLE
'Multi Site Origin Algorithm' is removed in delivery service UI in traffic_ops in TC-2.1

### ISSUE THREAD

**Issue by yorma** [apache/incubator-trafficcontrol#1173]
'Multi Site Origin Algorithm' field is not found in delivery service UI in traffic_ops in TC-2.1, which was existed in TC-1.7. In the MSO doc https://trafficcontrol.incubator.apache.org/docs/latest/admin/quick_howto/multi_site.html, it still mentions “Multi Site Origin Algorithm” drop-down list. 

The MSO doc is out of date?

**Comment by yorma** [comment]
refer to https://trafficcontrol.apache.org/docs/master/admin/quick_howto/multi_site.html?highlight=multi%20site, close this issue.

**Comment by smalenfant** [comment]
The graphic in section 4 needs updated.

**Comment by smalenfant** [comment]
Also Section 6 needs updated. `Select an option from the "Multi Site Origin Algorithm" drop-down list. Four MSO algorithms are supported:`

**Comment by dg4prez** [comment]
I'll update this within the next couple of days or so.

**Comment by rob05c** [comment]
Fixed in #1870
