### ISSUE TITLE
parent cachegroup is required for all cachegroup types in portal

### ISSUE THREAD

**Issue by DylanVolz** [apache/incubator-trafficcontrol#1183]
With a db with no cachegroups you cannot create any cachegroups via the portal because you cannot select a parent cachegroup. 

If the type is set to mid_loc (and perhaps others) parent cachegroup should not be required.

**Comment by mitchell852** [comment]
@DylanVolz - it looks like parentcachegroupid is not required for a cachegroup create/update so maybe just remove the requirement from the UI field altogether

https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/API/Cachegroup.pm#L456
