### ISSUE TITLE
ASN APIs: CRUD

### ISSUE THREAD

**Issue by mitchell852** [apache/incubator-trafficcontrol#1206]
- [x] get /api/$version/asns
- [x] get /api/$version/asns/:id
- [x] post /api/$version/asns
- [x] put /api/$version/asns/:id
- [x] delete /api/$version/asns/:id

post, put and delete should create a change log entry using the change log framework.

**Comment by knutsel** [comment]
I'm working on a re-purpose on the ASN table, so I'm claiming this one.
