### ISSUE TITLE
TO golang proxy logging sensitive data

### ISSUE THREAD

**Issue by elsloo** [apache/incubator-trafficcontrol#1216]
The Traffic Ops golang proxy appears to be logging some sensitive information contained in the configuration. Specifically this: `log.Infof("Using Config: %+v\n", cfg)` is writing sensitive information. We should scrub the config of sensitive information before logging and/or log this at a level other than `INFO` if we don't want to scrub the data.

**Comment by dewrich** [comment]
We're testing this PR now which should solve this issue https://github.com/apache/incubator-trafficcontrol/pull/1218/files#diff-5351d719d1ed997e55a0756cb19ec457L68

See #1218
