### ISSUE TITLE
Parameter APIs: CRUD

### ISSUE THREAD

**Issue by mitchell852** [apache/incubator-trafficcontrol#1335]
- [x] get /api/$version/parameters
- [x] get /api/$version/parameters/:id
- [x] post /api/$version/parameters
- [x] put /api/$version/parameters/:id
- [x] delete /api/$version/parameters/:id

**Comment by mitchell852** [comment]
@dangogh - see #1363

**Comment by dangogh** [comment]
fixed in #1950
