### ISSUE TITLE
Traffic Ops Golang Gzip incorrectly sets Content-Type, not Content-Encoding

### ISSUE THREAD

**Issue by rob05c** [apache/incubator-trafficcontrol#1354]
Traffic Ops Golang is incorrectly setting `Content-Type: gzip` when it gzips the body, not `Content-Encoding: gzip`. This violates RFC 7231 and conflicts with the Content-Type set by Handlers.

This is a critical bug, and breaks clients relying on the Encoding or Type to decode or display the data.

Fix is changing https://github.com/apache/incubator-trafficcontrol/blob/13b20c748b9bfe872a3bc3d5d7bec001ab8e4278/traffic_ops/traffic_ops_golang/wrappers.go#L189

`w.Header().Set(api.ContentType, api.Gzip)` to `w.Header().Set("Content-Encoding", api.Gzip)`

**Comment by mitchell852** [comment]
@rob05c - if this is indeed critical can you apply the 'critical' label?

**Comment by dewrich** [comment]
resolved by #1359
