### ISSUE TITLE
Failure in launching traffic-portal in dev-environment

### ISSUE THREAD

**Issue by nir-sopher** [apache/incubator-trafficcontrol#1379]
I'm synced to 2.1.x latest. Ran grunt to launch the portal and the below appears  in the output. Probably as a result of the error, the portal show blank screen.

Running "browserify2:app-dev" (browserify2) task
>> Error: module "./modules/private/monitor/map" not found from "/root/work/git/traffic_control/traffic_portal/app/src/app.js"
File written to: ./app/dist/public/resources/assets/js/app.js

**Comment by mitchell852** [comment]
This will fail in more than a dev environment. Needs to be fixed ASAP.

**Comment by hbeatty** [comment]
@mitchell852 I'm assuming this doesn't exist in master since you only oped the one PR. Closing issue.
