### ISSUE TITLE
Traffic Ops internal error on api/1.2/riak/stats

### ISSUE THREAD

**Issue by dangogh** [apache/incubator-trafficcontrol#1428]
Just running some random tests on the api on current master (2.2) of Traffic Ops and got this error:
```
Traffic Ops fatal error occurred while processing your request.
<br />
<hr />
Error at line 31 (	return $self-&gt;success( decode_json($content) );)
```

**Comment by mitchell852** [comment]
@dangogh  - can you put a severity level label on this? trivial, minor, major, critical...

**Comment by dangogh** [comment]
I put a label of minor on it -- I don't know where it's being used if at all...

**Comment by dangogh** [comment]
fyi -- it still exists on master as of today

**Comment by dneuman64** [comment]
As far as I know we are not using this endpoint for anything in Traffic Ops.  I believe the only reason it is in the code is because we were using it when we were first integrating with Riak.  As far as I am concerned, this endpoint can be removed.

**Comment by rawlinp** [comment]
Might be easier to just fix it than deal with removing an API endpoint that might possibly be in use somewhere... see #1805
