### ISSUE TITLE
TO API/TPv2 should have some ability to default geo miss long/lat for a delivery service

### ISSUE THREAD

**Issue by mtorluemke** [apache/incubator-trafficcontrol#1434]
The mojo template for adding a delivery service has them hard-coded to Chicago: 

https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/templates/delivery_service/_form.html.ep

We should probably pull from a parameter, or something...

**Comment by mitchell852** [comment]
@mtorluemke - just curious. what are the impacts if a delivery service is created with miss latitude/longitude set to null? where does the request get routed to?
