### ISSUE TITLE
Need to be able to define default lat/lon for CLIENT_STEERING DSs

### ISSUE THREAD

**Issue by dneuman64** [apache/incubator-trafficcontrol#1452]
Currently the UIs (TO and TP) do not allow you to enter a default lat/lon for CLIENT_STEERING DSs.  This means that if there are no geo restrictions but a user ends up being a miss, the user will receive a 503 instead of being sent to some default location.

**Comment by mitchell852** [comment]
@dneuman64 - same with just STEERING DSs?

**Comment by dneuman64** [comment]
Yeah

**Comment by mitchell852** [comment]
for the Traffic Portal, take a look at form.deliveryService.DNS.tpl.html. you probably just need to add the appropriate html fields to form.deliveryService.Steering.tpl.html

**Comment by rawlinp** [comment]
So I dug into this a bit, and the Geo Miss Lat/Lon for a STEERING or CLIENT_STEERING Delivery Service is never actually used. Only the Geo Miss Lat/Lon from the steering targets are used.

For STEERING DSes, the Geo Miss Lat/Lon of the chosen target is used. For CLIENT_STEERING DSes, I think it will use the Geo Miss Lat/Lon of the first target (I'd have to dig a bit deeper to confirm this) when creating the list of target URLs. But, the point is this isn't a necessary field for either steering type.

**Comment by dneuman64** [comment]
Yeah, I think I figured that out after I submitted this issue and then forgot to close it.  I will close now, thanks for the input @rawlinp
