### ISSUE TITLE
Portal -- SSL certificates for HTTP* deliveryservices should be created as wildcards

### ISSUE THREAD

**Issue by dneuman64** [apache/incubator-trafficcontrol#1465]
When generating SSL certificates for a HTTP deliveryservice via Traffic Portal, the common name includes the routing name.  The common name should be a wildcard since the certs will potentially be on hundreds of servers.

**Comment by mitchell852** [comment]
maybe @DylanVolz can look at this one as he added the SSL cert functionality to TP and may be most familiar with the code.

**Comment by dneuman64** [comment]
I also noticed that TP will change the hostname to be incorrect if you paste certificates in for a HTTP DS.  This needs to be fixed before 2.2 is released
