### ISSUE TITLE
Traffic-Portal build fails - openssl issues 

### ISSUE THREAD

**Issue by nir-sopher** [apache/incubator-trafficcontrol#1471]
Trying to build 2.1.x latest (calling ./pkg) on my centos7 VM, I get the below error during traffic-portal build (due to the recent RedHat openssl issues).
npm: relocation error: npm: symbol SSL_set_cert_cb, version libssl.so.10 not defined in file libssl.so.10 with link time reference

I overcame the issue by changing the image in the Dockerfile to centos:7.4.1708

**Comment by mitchell852** [comment]
@nir-sopher - this good now? can you reference this issue in the PR you created for it?

**Comment by smalenfant** [comment]
@mitchell852 Isn't Centos:7 is actually the same as Centos:7.4.1708? I guess one needs to make sure they pull down the latest image.

```
$ docker run --rm -it centos:7 cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 
```

**Comment by nir-sopher** [comment]
It works well after the change.
