### ISSUE TITLE
Generate dynamic distribution list for tenant communications

### ISSUE THREAD

**Issue by thusai000** [apache/incubator-trafficcontrol#1479]
Traffic Portal now has the ability to list contact details of users/tenant admins. Would be nice to be able to aggregate all non-null/well-formatted email addresses from https://$trafficportalinstance/tenants/4/users in order to send communications regarding customer impacting maintenances/upgrades. Since tenant list is ever changing, this has to be made available as an on-demand, dynamic builder.

**Comment by mitchell852** [comment]
@thusai000 - at one point email was not a required field on a Traffic Ops user create/update. It is a required field now through the API (and as a result thru TP). My point is, ALL users should have an email address associated with them and if they don't, those users should be updated to add their email addresses. It's probably in your best interest to do some data cleanup and add emails to users that have no email.

As Traffic Ops evolves, data cleanup becomes a necessary thing to ensure the integrity of the TO data.
