### ISSUE TITLE
Add an Environment field to list of servers

### ISSUE THREAD

**Issue by thusai000** [apache/incubator-trafficcontrol#1519]
Add a field to designate environments. Would allow users to filter hosts per environment, maintaining huge list of inventory in wiki does not seem feasible:
https://$trafficportal/#!/servers

**Comment by mitchell852** [comment]
i'm not sure this makes sense to me. in your production traffic portal you "should" see only production servers at https://$trafficportal/#!/servers (production caches, production riaks, production influxes, etc)

whereas in your QA traffic portal, you "should" only see QA  servers at https://$trafficportal/#!/servers

is it really a use case that users manage servers across all environments in one instance of TO/TP?

**Comment by mitchell852** [comment]
closing per @thusai000

**Comment by thusai000** [comment]
after thinking about it, yes... doesn't make sense. pls close the issue don't see the option
