### ISSUE TITLE
401 Causes TM to lose visibility into TO API

### ISSUE THREAD

**Issue by elsloo** [apache/incubator-trafficcontrol#1523]
It appears that if Traffic Monitor is unable to authenticate with Traffic Ops at some point after doing so successfully in the past it will not recover. We should test more to confirm the behavior, then fix the bug as appropriate.

**Comment by rob05c** [comment]
TM uses the TO Client. The TO client never re-authenticates. It also never pings to refresh the cookie. If you make a client and wait 25 hours without requesting, the cookie will expire, and your client will be permanently dead.

We should fix both: automatically try to re-auth if it gets a 401 (and maybe 403?), and have a goroutine ping periodically (hourly?) to refresh the cookie.
