### ISSUE TITLE
Traffic Portal - Cloning Delivery Services sort order and dropping existing delivery services

### ISSUE THREAD

**Issue by saoyag001** [apache/incubator-trafficcontrol#1531]
1. When cloning delivery services, sort order in traffic ops is closest name wise at the top, then alphabetical order after that. in TP the order seems random, requiring to read through the entire list to find the correct server to clone.
2. After choosing delivery services to clone, it should wipe out the existing delivery services and replace with the new "Cloned" list, however it keeps the existing and adds the cloned list.

Traffic Portal Version: 2.2.0-7240.37c0bbe7.el7

**Comment by mitchell852** [comment]
Is this what you are talking about?

/#!/servers/:serverId/delivery-services, then click the 'More' and then 'Clone Delivery Service Assignments'

![image](https://user-images.githubusercontent.com/251272/32732341-7d00a744-c849-11e7-9128-eac6a771ce4c.png)

Then you get

![image](https://user-images.githubusercontent.com/251272/32732538-21f9f642-c84a-11e7-8835-107597a9a456.png)

1. You are saying the target servers are out of order, right?
2. When you clone ds's from server A to server B, server B's ds's DO get wiped out and replaced with the ds's of server A. I just verified that.

**Comment by mitchell852** [comment]
this bug is related to #1550
