### ISSUE TITLE
TP unique value error trying to store NULL IPv6 address for server

### ISSUE THREAD

**Issue by guzzijason** [apache/incubator-trafficcontrol#1533]
While updating MSO origin server properties in the new TP UI, I am getting 500 errors when trying to modify the second of the two servers. It appears that it is attempting to store a "null" IPv6 address for the server (server does not have IPv6 address).

```
[2017-11-13 20:41:18,833] [ERROR] DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  duplicate key value violates unique constraint "idx_140441_ip6_profile"
DETAIL:  Key (ip6_address, profile)=(, 192) already exists. [for Statement "UPDATE server SET ilo_username = ?, ip6_address = ? WHERE ( ( cachegroup = ? AND id = ? AND profile = ? AND status = ? AND type = ? ) )" with ParamValues: 1='None', 2='', 3='509', 4='2077', 5='192', 6='2', 7='3'] at /opt/traffic_ops/app/lib/API/Server.pm line 235
[2017-11-13 20:41:18,836] [ERROR]
```
We should not be attempting to store a new IPv6 address here, as it shouldn't have a value at all (and is not changing).

Problem does not seem to exist in the legacy Traffic Ops UI.

**Comment by mitchell852** [comment]
There is a unique constraint on the server table which is ip6_address + profile, therefore you can't have 2 servers with null ip6_address + profile A (for example) however that seems silly so i think this unique constraint simply needs to be modified to only be enforced if ip6_address != null.

looks like you can do a conditional constraint https://www.postgresql.org/docs/9.6/static/ddl-constraints.html using the CHECK function.

**Comment by mitchell852** [comment]
actually, this is occurring because a empty string is being passed in and multiple rows in the server table where ip6=empty string and profile=X is a violation of the unique constraint.

**Comment by mitchell852** [comment]
this is related to #1535
