### ISSUE TITLE
We need better feedback for why create/update/save buttons are disabled in Traffic Portal.

### ISSUE THREAD

**Issue by alficles** [apache/incubator-trafficcontrol#1537]
When buttons are disabled in Traffic Portal, it's often unclear which field is violating which constraint. This showed up fairly recently during an upgrade, when the Geo Miss Lat/Long fields were upgraded to "required". This effectively made all our previous DSs that did not contain these fields un-editable, with no UI feedback indicating why this was so.

**Comment by rawlinp** [comment]
I created #1538 before I saw this issue, so I closed that one as a duplicate.

**Comment by benjamingr** [comment]
Hey, I can take a look if this isn't urgent (assuming this is in Node.js land)

**Comment by mitchell852** [comment]
hi @benjamingr thanks for the offer but i got a PR in already for it. and FYI, it's not nodejs per se but rather angularjs. you can take a look at the PR if you're curious.
