### ISSUE TITLE
TO/TP - query string handling options force cacheurl on option 1

### ISSUE THREAD

**Issue by ezelkow1** [apache/incubator-trafficcontrol#1554]
If option 1 is chosen on the query string handling for a delivery service in TO or TP this will force an insertion of a generic cacheurl line which uses a default qstring.config file.  When we eventually switch to ATS7 this will break all DS's using this option since cacheurl will no longer work and cachekey must be used

**Comment by rob05c** [comment]
Fixed in #1602
