### ISSUE TITLE
TrafficPortal DNS Bypass TTL storing empty string 

### ISSUE THREAD

**Issue by tyagian** [apache/incubator-trafficcontrol#1569]
When I add something to DNS Bypass TTL and then delete it. It will end up with 5xx internal server error when I do submit to create Delivery Service.

**Comment by mitchell852** [comment]
This is because the create/delete delivery service api can't handle empty strings where an integer is expected. The API should convert empty strings to null so it can insert a null into the database instead. This should be done globally in my opinion.

**Comment by mitchell852** [comment]
or better yet, the api should reject empty strings where integers are expected.
