### ISSUE TITLE
Traffic Ops update_status endpoint returns empty response without use_reval_pending parameter set in global profile

### ISSUE THREAD

**Issue by rivasj** [apache/incubator-trafficcontrol#1595]
The endpoint at: /api/1.3/servers/$hostname_short/update_status returns an empty response if use_reval_pending parameter is not in the global profile. This is causing the ORT script to fail when run with the 'syncds' flag.

The perl endpoint at: /update/$hostname did not require this parameter to exist.

**Comment by mitchell852** [comment]
@DylanVolz - can you look at this?

**Comment by DylanVolz** [comment]
This is being defaulted in the query now on master and the pull request here: https://github.com/apache/incubator-trafficcontrol/pull/1596 will fix the column name change introduced by the coalesce.

**Comment by mitchell852** [comment]
@rivasj - can you close this if all is good now?

**Comment by dg4prez** [comment]
It looks to me like the go version of the API is returning a value for reval_pending and parent_reval_pending regardless of the status or existence of use_reval_pending in global.  This is not how the 1.2 api functioned, nor is it how ORT functions - if the parameter exists, it assumes that reval_pending is in use and does not check revalidation status.  This will absolutely break invalidation unless reval pending is actually enabled.  For backwards compatibility, the API needs to be updated to remove this value from the json, or we need to modify the ort script to change how it functions.

**Comment by dg4prez** [comment]
https://github.com/apache/incubator-trafficcontrol/pull/2158
