### ISSUE TITLE
Improve UI testing with protractor.

### ISSUE THREAD

**Issue by trevorhays** [apache/incubator-trafficcontrol#1597]
Create an initial set of tests in protractor to begin automating the testing of our UI.

1.  Successfully Login. 
2.  Login with a bad user/password

**Comment by trevorhays** [comment]
PR - https://github.com/apache/incubator-trafficcontrol/pull/1598

**Comment by mitchell852** [comment]
@trevorhays - PR has been merged. can you close this?
