### ISSUE TITLE
API: Server API sets xmpp_id to null

### ISSUE THREAD

**Issue by smalenfant** [apache/incubator-trafficcontrol#1620]
We have been moving servers using the API (Traffic Ops 2.1). When the server were created, we noted that the HTTP request consistent hashing was not working anymore. We discovered that the xmpp_id was set to null.

This field was present in the CR-Config under the server hostnames : 
`"hashId": null,`

**Comment by elsloo** [comment]
We should fix this on both sides.. TR and the API.

**Comment by elsloo** [comment]
Opened #1628 to address the Traffic Router side of this.

**Comment by rob05c** [comment]
We'll essentially get this for free, when the Server create/POST route is moved to `traffic_ops_golang`.

Specifically, the insert should set the `xmpp_id` to the `host_name` if it's null. It should probably also respect the `xmppId` JSON field when sent, as returned by the GET endpoint.

**Comment by rob05c** [comment]
@DylanVolz

**Comment by rob05c** [comment]
Fixed in #1859
