### ISSUE TITLE
TP: Bug when updating a user role a new password must be entered 

### ISSUE THREAD

**Issue by ryandurfey** [apache/incubator-trafficcontrol#1655]
TP: Bug when updating a user role in TP, a new password must be entered for the user before it will allow you to update the user.  Looks like some type of validation setting.

**Comment by mitchell852** [comment]
just so i understand the use case.

1. you registered a new user with email, role and tenant
2. you realized you gave the user the wrong role so you went to edit the user's role and now password is required..

**Comment by ryandurfey** [comment]
Yep.  Any time I go into an existing user to change something the password field is empty, however a valid entry in that field appears to be required to enable the update button.

**Comment by mitchell852** [comment]
fyi as a workaround you can simply send the user registration a 2nd time with the role/tenant you want but this should be fixed.
