### ISSUE TITLE
URI Signing doesn't assign parameters to profiles

### ISSUE THREAD

**Issue by smalenfant** [apache/incubator-trafficcontrol#1662]
Once you create the URI Signing Keys for a delivery service, ORT will complain about not being able to create the configuration on disk and also Traffic Server will complain about not being able to load the plugin.

The current workaround seems to be creating link a parameter in each Edge profile that requires the URI Signing config for that specific delivery service. Prone to errors.

Traffic Ops was usually dealing with creating parameters before, but URI signing is only configurable by Traffic Portal.

**Comment by mitchell852** [comment]
@alficles @PSUdaemon @jrushford thoughts?

**Comment by alficles** [comment]
This is really a regression, from a user point of view. The new feature, URI Signing, is replacing the old one and should really have the same behaviour. The existing workflow is really bad and we should port that behaviour forward.

**Comment by mitchell852** [comment]
@smalenfant - can you put a "severity" label on this?

**Comment by rob05c** [comment]
Moving to a future release. It really is mostly a regression, but it's not that clean-cut, as URI Signing is a new feature. But unfortunately we're hard-pressed to find the resources to add/fix this soon. If anyone feels this really needs to be in 2.3, feel free to move it back and we can discuss
