### ISSUE TITLE
Traffic Portal doesn't restart using systemctl

### ISSUE THREAD

**Issue by smalenfant** [apache/incubator-trafficcontrol#1664]
If you restart using systemctl, the process spawns a new daemon but never kills the old one, resulting in multiple process running and logs filing up with `EADDRINUSE`.

It also doesn't stop/start using systemctl. Which causes problem on a Centos 7 and the Ansible "service" module.

**Comment by mitchell852** [comment]
I guess I always do it like:

sudo service traffic_portal start/stop/restart/status

**Comment by dangogh** [comment]
@smalenfant I can't reproduce this on master.   Can you do the following on the problem system and post the results? 
```
-bash-4.2$ sudo systemctl status traffic_portal|grep Active
   Active: active (running) since Mon 2018-01-22 15:44:40 UTC; 5min ago
-bash-4.2$ sudo systemctl stop traffic_portal
-bash-4.2$ sudo systemctl status traffic_portal|grep Active
   Active: inactive (dead) since Mon 2018-01-22 15:49:56 UTC; 2s ago
-bash-4.2$ sudo systemctl start traffic_portal
-bash-4.2$ sudo systemctl status traffic_portal|grep Active
   Active: active (running) since Mon 2018-01-22 15:50:05 UTC; 2s ago
```

**Comment by smalenfant** [comment]
@mitchell852 Let me test again, but it might be an issue on upgrading only.

**Comment by smalenfant** [comment]
I've retested. All is fine. Not sure why I could not reproduce. Closing.
