### ISSUE TITLE
TO: "Server Checks" page could not load

### ISSUE THREAD

**Issue by zhilhuan** [apache/incubator-trafficcontrol#1703]
Found in TC 2.1

Errors in /var/log/traffic_ops/extensionCheck.log:

Can't use string ("1") as an ARRAY ref while "strict refs" in use at /opt/traffic_ops/app/bin/checks/ToCHRCheck.pl line 96.
2017/12/26 00:09:01 $VAR1 = {
          'code' => '403',
          'message' => 'Forbidden'
        };

**Comment by mitchell852** [comment]
@zhilhuan - can you close this?

**Comment by zhilhuan** [comment]
@mitchell852 closed. Thanks!
