### ISSUE TITLE
Deleting a header rewrite rule causes ORT problems

### ISSUE THREAD

**Issue by jhg03a** [apache/incubator-trafficcontrol#1744]
Use case:
1. Run ORT syncds on an edge and observe it runs without error
2. On a delivery service that has never had an edge header rewrite rule, add an edge header rewrite rule
3. Queue a server used in step 1
4. Run ORT syncds and observe it creates the hdr_rw_<ds>.conf file and runs without error
5. Remove the edge header rewrite rule
6. Queue the server used in step 1
7. Run ORT syncds with warn and observe errors similar to below

Workaround:
8. Instead of deleting the edge header rw in 5, replace it with the single character #.  This introduces a secondary warning that can be ignored below.

Failure Errors:
```Use of uninitialized value in concatenation (.) or string at /opt/ort/traffic_ops_ort.pl line 2543.
Use of uninitialized value $dir in -d at /opt/ort/traffic_ops_ort.pl line 647.
Use of uninitialized value $dir in concatenation (.) or string at /opt/ort/traffic_ops_ort.pl line 650.
/bin/mkdir: missing operand
Try '/bin/mkdir --help' for more information.
Use of uninitialized value $dir in pattern match (m//) at /opt/ort/traffic_ops_ort.pl line 651.
Use of uninitialized value $dir in pattern match (m//) at /opt/ort/traffic_ops_ort.pl line 655.
Use of uninitialized value $result in pattern match (m//) at /opt/ort/traffic_ops_ort.pl line 2510.
Use of uninitialized value $size in numeric eq (==) at /opt/ort/traffic_ops_ort.pl line 2516.
Use of uninitialized value $url in concatenation (.) or string at /opt/ort/traffic_ops_ort.pl line 2517.
ERROR URL:  returned empty!
ERROR /opt/trafficserver/etc/trafficserver//remap.config needs touched. Doing that now.
```

Workaround Warning:
```WARN URL: /api/1.2/cdns/title-vi/configfiles/ats/sample_ds.config returned only the header.
ERROR Lines for /opt/trafficserver/etc/trafficserver/sample_ds.config from Traffic Ops do not match file on disk.
ERROR Config file sample_ds.config line only in TrOps:      #
ERROR Creating backup of file on disk for sample_ds.config.
ERROR Creating backup of file in TrOps for sample_ds.config.
```

**Comment by jhg03a** [comment]
If I'm not mistaken, the ORT failure message looks exactly the same as what happens if you're missing a 'location' parameter.

**Comment by jhg03a** [comment]
I would expect deleting the header rewrite to also delete the hdr_rw_sample_ds.conf file (or at least not throw errors).  Likewise I would expect the workaround to not throw that false warning.

**Comment by mitchell852** [comment]
@jhg03a - would you consider this a bug and if so what severity level?

Is 8 the only workaround? If not, can you document any other workarounds?

**Comment by jhg03a** [comment]
Yes, I would consider this a bug.  Two in fact with the false warning.  From a severity perspective, I would expect anyone who uses TC and rewrite rules to experience this oddity.  I'm not sure what the fallout is on the primary error, however if it is the same effect as when a `location` param is missing that would lead to unexpected behavior which is not good.  I would rate this somewhere in the middle to lower priorities because I try not to use high priorities and this has a workaround.

I'm not currently aware of other workarounds.

**Comment by mitchell852** [comment]
I think this line needs to be fixed

https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm#L2665

to test the value better. empty string returns true in this case.
