### ISSUE TITLE
/traffic_ops/app/public/images/ contains non-free images

### ISSUE THREAD

**Issue by alficles** [apache/incubator-trafficcontrol#1750]
This folder appears to contain some old and unused (at least as far as my crude grep goes) files that I am pretty sure are not distributable under the Apache license. Among them are logos for Comcast and specific Comcast departments. Other images, I've had trouble finding concrete sources for, so I'm not sure what the license on them is.

**Comment by rob05c** [comment]
Ok, we discussed this, and it sounds like most of the images were hand-made for Traffic Control several years ago when it was first open sourced.

The ones that weren't were specifically graph.png and info.png. I've made a PR with new images the same size from known, valid licenses
