### ISSUE TITLE
SSL cert page uses wrong hostname on update.

### ISSUE THREAD

**Issue by jpappa200** [apache/incubator-trafficcontrol#1855]
If the delivery service has a host regex configured. when pasting a new SSL certificate traffic portal will change the hostname to the host regex name. ORT looks for the default delivery url in the hostname field. This will cause ORT to not find the certificate and fail. 

before
version = 13
hostname = edge.aywa-vod.top.comcast.net

after
version = 14
hostname = cdn2.aywa.com

**Comment by mitchell852** [comment]
@jpappa200 - every ds has a host regex configured, right? you mean if a ds has multiple host regexes...

**Comment by jpappa200** [comment]
yes if multiple are configured it's using the wrong one.

**Comment by mitchell852** [comment]
@jpappa200 - i can't seem to recreate this bug. I'll reach out to you and we can try in our staging environment.
