### ISSUE TITLE
url parameters for last_updated are not parsed correctly

### ISSUE THREAD

**Issue by DylanVolz** [apache/incubator-trafficcontrol#1858]
url encoding the last_updated field of an hwinfo or parameters object and supplying it in the url parameters to create a where clause is expected to return the object but currently returns an empty set due to no match.

**Comment by dangogh** [comment]
this is a regression from 2.1,  so should be fixed for 2.2

**Comment by DylanVolz** [comment]
This is was due to user error while testing. Upon retesting last_updated filtering is working fine.
