### ISSUE TITLE
Request parent.conf via api, if there is no assigned ds's, need to error out clearly.

### ISSUE THREAD

**Issue by jdawgitsome** [apache/incubator-trafficcontrol#1897]
When requesting parent.conf via api, and there is no assigned ds's, traffic ops needs to handle and error out clearly.

Currently the error that is reported back is the following:

Traffic Ops fatal error occurred while processing your request. 
Error at line 2468 (    foreach my $ds ( sort @{ $data->{dslist} } ) {) 
Can't use an undefined value as an ARRAY reference at /opt/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm line 2468.

**Comment by dg4prez** [comment]
https://github.com/apache/incubator-trafficcontrol/pull/1898
