### ISSUE TITLE
TO 2.1 install error

### ISSUE THREAD

**Issue by RSK14** [apache/incubator-trafficcontrol#1904]
![capture](https://user-images.githubusercontent.com/35360464/36538703-75d19ab8-17fa-11e8-96a2-87d78d4c26f8.PNG)
![capture1](https://user-images.githubusercontent.com/35360464/36538704-7609415c-17fa-11e8-875e-e01a3568c142.PNG)

Dear Team,

Unable to install Traffic ops 2.1 version (CentOS Linux release 7.4.1708 (Core) )

RPM: traffic_ops-2.1.0-6807.1dcd512f.el7.x86_64.rpm -- i installed  this rpm.

i getting below error.Could you please tell me how to fix this issue. 

Thu Feb 22 07:00:47 2018: WARN Log file '/var/log/traffic_ops/cpan.log' does not exist - not rotating log
Thu Feb 22 07:00:47 2018: INFO No input file given - using defaults
Thu Feb 22 07:00:48 2018: ERROR Failed to install Traffic Ops Web dependencies, check the console output and rerun postinstall once you've resolved the error
Thu Feb 22 07:03:22 2018: INFO Starting postinstall
Thu Feb 22 07:03:22 2018: INFO Debug is on
Thu Feb 22 07:03:22 2018: WARN Log file '/var/log/traffic_ops/cpan.log' does not exist - not rotating log
Thu Feb 22 07:03:22 2018: INFO No input file given - using defaults
Thu Feb 22 07:03:22 2018: ERROR Failed to install Traffic Ops Web dependencies, check the console output and rerun postinstall once you've resolved the error

Successfully installed goose to /opt/traffic_ops/go/bin/goose
unzipping log
Starting postinstall
Debug is on
Log file '/var/log/traffic_ops/cpan.log' does not exist - not rotating log
No input file given - using defaults
Got HTTP 200 response for 'https://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js'
Failed to install Traffic Ops Web dependencies, check the console output and rerun postinstall once you've resolved the error
Died at /opt/traffic_ops/install/lib/InstallUtils.pm line 62.

Thanks 

Satheesh R

**Comment by dangogh** [comment]
I've renamed the issue to indicate more precisely what you're asking for.   To retry installing the web dependencies,  you can try this:  `sudo /opt/traffic_ops/install/bin/download_web_deps`.   If you see an error,  please post the error here.  I just tried it myself on a new Centos VM and saw no error.

**Comment by dangogh** [comment]
also,  your log message is missing the real error from the image --

```
Can't call method "reset" on an undefined value at .../IO/Uncompress/Base.pm ...

```

**Comment by dangogh** [comment]
For further assistance,  I suggest joining the mailing list or slack channel -- you'll get much more immediate help there.  You can get info on those here:  http://trafficcontrol.incubator.apache.org/ask/index.html

**Comment by achilles-liu** [comment]
Dear team,
I met same question.
RMP :  traffic_ops-3.0.0-10017.5fd57f36.el7.x86_64.rpm

[root@localhost js]# /opt/traffic_ops/install/bin/postinstall
Carton is up to date. (v1.0.34)
Installing modules using /opt/traffic_ops/app/cpanfile
Complete! Modules were installed into /opt/traffic_ops/app/local
Now installing goose
Successfully installed goose to /opt/traffic_ops/go/bin/goose
unzipping log
Starting postinstall
Debug is on
Log file '/var/log/traffic_ops/cpan.log' does not exist - not rotating log
No input file given - using defaults
Got HTTP 0 response for 'https://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js'
Failed to install Traffic Ops Web dependencies, check the console output and rerun postinstall once you've resolved the error
Died at /opt/traffic_ops/install/lib/InstallUtils.pm line 62.
[root@localhost js]# /opt/traffic_ops/install/bin/download_web_deps
Got HTTP 0 response for 'https://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js'
[root@localhost js]#

Could you please tell me how to fix this issue?
