### ISSUE TITLE
TO API - Provide ability to associate roles w/ capabilities

### ISSUE THREAD

**Issue by mitchell852** [apache/incubator-trafficcontrol#2035]
~~Add one or more capabilities to a role <-- admin role~~
~~Remove one or more capabilities from a role <-- admin role~~

- [ ] Add the ability to update the capabilities associated with a role <-- admin role required

See comment below from @DylanVolz

**Comment by DylanVolz** [comment]
I think these can both be implemented on an update to a Role, by adding a field that is an array of Capabilities to the role JSON.

**Comment by mitchell852** [comment]
I'm going to close this because this functionality is captured with #2033
