### ISSUE TITLE
deleting inactive delivery services requires double confirmation

### ISSUE THREAD

**Issue by saoyag001** [apache/incubator-trafficcontrol#2055]
to delete a DS, you have to delete it, type ds name"xml-id", then go to ds requests, delete it again type ds name plus delete request.  "xml-id delete request" can this be set to only go through that on an active DS?

**Comment by mitchell852** [comment]
@saoyag001 - why are you deleting a ds and then deleting the ds request?

if you are trying to delete a delivery service, you need to:

1. first delete the ds (which will create a ds request to delete the  ds)
2. fulfill (not delete) the ds request

**Comment by saoyag001** [comment]
negative, this is for an existing DS.
example Existing ds xml-id is no longer needed, cutomer requests it be deleted.
1. inactivate and remove servers from DS
wait a week or so to ensure they really dont need it
2. delete it.
deleting puts it in the delivery service requests queue
3. then assign to you and delete

**Comment by mitchell852** [comment]
#3 should be 

3. then assign to you and "fulfill" (not delete)

**Comment by mitchell852** [comment]
this would be satisfied by #2174 so i'm going to close this issue
