### ISSUE TITLE
Trailing slash in DS origin URL breaks MSO parent.config

### ISSUE THREAD

**Issue by guzzijason** [apache/incubator-trafficcontrol#2062]
Had an issue today while trying to convert an existing DS to use MSO. The `parent` field in parent.config kept coming up blank. Noticed that the DS had a trailing `/` on the origin URL. After removing that, the MSO configs in parent.config looked good. Re-added the trailing `/` just to confirm behavior, and parent.config broke again in the same way.

**Comment by mitchell852** [comment]
Enforcing this in TP is a nice to have but at the very least it needs to be enforced in the API.

**Comment by mitchell852** [comment]
@guzzijason - just so i'm clear. the origin server base URL can never end with a forward slash regardless of whether the ds is mso or not

![image](https://user-images.githubusercontent.com/251272/38034562-cc11e098-325f-11e8-980a-8752ed1fb9db.png)

**Comment by mitchell852** [comment]
FYI - i think this is the regex in the API needs to be updated

https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/API/Deliveryservice.pm#L1581

now the question is...what's a good regex for URL validation....

I found this: https://mathiasbynens.be/demo/url-regex

@dewrich @dangogh any ideas?

**Comment by dangogh** [comment]
@mitchell852 my feeling is that a url with a trailing slash is valid and that the code generating the parent.config needs to be able to handle it properly.   Perhaps need to look there first.
