### ISSUE TITLE
Read method on api/1.3/types does not return 'lastUpdated'

### ISSUE THREAD

**Issue by ajschmidt** [apache/incubator-trafficcontrol#2153]
api/1.3/types returns an empty value for the 'lastUpdated' field where version api/1.2 returns a valid time stamp. The 'lastUpdate' value needs to be added to the 1.3 version in Go and then the api/1.2 version needs to be replaced with the Go implementation and the Perl version removed.

**Comment by mitchell852** [comment]
@ajschmidt will be working on this

**Comment by rob05c** [comment]
Fixed by #2155 in 58ab7c2aeb6e7c7a97a5afbdaf463562ea00e20d
