### ISSUE TITLE
TO/TP should allow for a configuration such that admins do not have to submit DSRs

### ISSUE THREAD

**Issue by mtorluemke** [apache/incubator-trafficcontrol#2174]
Maybe this is already covered by the ongoing roles & responsibilities effort?

**Comment by mitchell852** [comment]
We could do this a couple of ways:

1. If user.role=admin, then skip DSR
2. if user.capabilities has deliveryservice-write, then skip DSR

# 2 requires roles/capabilities to be done which is probably a few weeks off still. 

# 1 can be done for the short-term pretty easily but when roles/capbilities are done, it will have to be switched to # 2.

**Comment by trevorhays** [comment]
Can we follow the same DS request flow but if the user=admin then automatically fulfill the DS requests?  That way we don't have different workflows to maintain depending on the user's role.

**Comment by mitchell852** [comment]
Implemented as such:

If DSR is enabled and user.role=admin, then DSR is created/closed in the background.
