### ISSUE TITLE
TP: sorting of cache group list is no longer alphanumeric

### ISSUE THREAD

**Issue by guzzijason** [apache/incubator-trafficcontrol#2260]
Traffic Portal Version: 2.3.0-8247.fb69f019.el7

Cache groups used to sort by alpha, but now appear to be unsorted, making it difficult to navigate drop-down menus in the UI.

Looking at the edit server UI, the "type" field suffers the same affliction. However, the "profile" field does appear to sort properly.

**Comment by mitchell852** [comment]
Perl used to have a default orderby when the results of a collection was returned. Go apparently does not have this default orderby so I will simply add a ?orderby=X to all the calls that TP makes where a collection is returned.
