### ISSUE TITLE
Download ISO should actually download the ISO

### ISSUE THREAD

**Issue by dneuman64** [apache/incubator-trafficcontrol#2275]
Currently, when you generate an ISO you are given a link to download the ISO.  If you are running a traffic ops in a HA fashion, it is no guarantee that the link will send you to the same Traffic Ops meaning that there is a possibility that you will not be able to download the ISO.  Instead of giving the user a link to download the ISO, traffic ops should just let the user download the ISO.  This would resolve the issue where you could get sent to a different Traffic Ops to download the ISO.

**Comment by mitchell852** [comment]
@dneuman64 - this was already captured in #1616 and @rivasj will be looking at this, so i'm going to close this.
