### ISSUE TITLE
Increase server hostname max length

### ISSUE THREAD

**Issue by jhg03a** [apache/incubator-trafficcontrol#2279]
As a CDN SRE I want to be able to supply an arbitrarily long hostname.  Today I actually only need 5 more characters, but this seems like a hidden limit that will just cause more problems later.  Today I don't have this issue with the domainname field, but it would seem to be the same issue.

**Comment by mitchell852** [comment]
Are you referring to the field in traffic portal?

**Comment by rawlinp** [comment]
Yeah I think since the DB type is just `text` we should be able to bump up the artificial limit in TP.

**Comment by mitchell852** [comment]
there's probably a maxLength attribute in TP.  you want to remove that @rawlinp ?

**Comment by rawlinp** [comment]
Sure, just opened #2281 to increase both limits in TP to 100.
