### ISSUE TITLE
GET /api/1.3/cachegroups doesn't support filtering by type

### ISSUE THREAD

**Issue by rawlinp** [apache/incubator-trafficcontrol#2387]
The Perl version of the cachegroups API supported filtering by `type` using a query parameter, but the current golang version of the API doesn't support this. At a minimum this is breaking `https://<insert Traffic Portal URL>/#!/types/<insert type ID>/cache-groups` in the Traffic Portal; rather than just showing cachegroups of that type ID, it shows _all_ cachegroups.

**Comment by mitchell852** [comment]
https://<insert Traffic Portal URL>/#!/types/<insert type ID>/cache-groups

calls this api:

GET api/1.3/cachegroups?type=6

like @rawlinp said, the 'type' query parameter is being ignored
