### ISSUE TITLE
[TC-488] Docs - Multi Site Origin not up to date

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#878]
<p>Current documentation for multi site origin is confusing/wrong/out of date:</p>

<p>   <a href="https://github.com/apache/incubator-trafficcontrol/blob/master/docs/source/admin/quick_howto/multi_site.rst" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/docs/source/admin/quick_howto/multi_site.rst</a><br/>
   Bottom has steps that references configuration that I think has been replaced with delivery service profiles.<br/>
   <a href="https://github.com/apache/incubator-trafficcontrol/blob/master/docs/source/admin/traffic_ops/using.rst" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/docs/source/admin/traffic_ops/using.rst</a><br/>
   mentions the new delivery service profile pieces, but not the cachegroup side of multi-site configuration.</p>

Author: Matt Mills
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-488">https://issues.apache.org/jira/browse/TC-488</a>
Found Version: 2.1.0

**Comment by dneuman64** [comment]
@dg4prez can you update the docs?

**Comment by dg4prez** [comment]
https://github.com/apache/incubator-trafficcontrol/pull/828 merged.
