### ISSUE TITLE
[TC-490] mso.qstring_handling parameter is checked but not documented

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#879]
<p>mso.qstring_handling not listed in docs, seems to be defined elsewhere as psel.qstring_handling<br/>
   but MID parent selection code checks if mso.qstring_handling is not defined</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
   my $qsh            = $ds-&gt;{'param'}-&gt;{'parent.config'}-&gt;{'mso.qstring_handling'};
   my $parent_qstring = <span class="code-quote">"ignore"</span>;                                                      # <span class="code-keyword">default</span> is ignore, unless <span class="code-keyword">for</span> alg consistent_hash
   <span class="code-keyword">if</span> ( !defined($qsh) &amp;&amp; $mso_algorithm eq 'consistent_hash' &amp;&amp; $ds-&gt;{qstring_ignore} == 0 ) {
      $parent_qstring = 'consider';
   }

</pre>
</div></div>

<p>The parameter is unlikely to ever exist, since it's not documented anywhere, but either way either the code should be corrected or the documentation should be.</p>

Author: Matt Mills
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-490">https://issues.apache.org/jira/browse/TC-490</a>
Found Version: 2.1.0

**Comment by dneuman64** [comment]
@dg4prez can you update the docs?

**Comment by dg4prez** [comment]
This has been updated in the docs already and is fixed in https://github.com/apache/incubator-trafficcontrol/pull/1310.  Please note that this only affected the UI code which is deprecated.
