### ISSUE TITLE
[TC-489] Multi Site Origin - Invalid default values for multiple config params

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#880]
<p>Several of the multi site origin parameters default to 0 (including mso.algorithm, possibly others ), which is an invalid argument.<br/>
   valid values: true, strict, proxy1, false, consistent_hash</p>

<p>   <a href="https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm#L2051" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm#L2051</a></p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
   L2051: $text .= <span class="code-quote">"$parents round_robin=$mso_algorithm qstring=$parent_qstring go_direct=<span class="code-keyword">false</span> parent_is_proxy=<span class="code-keyword">false</span>"</span>;
</pre>
</div></div>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
   parent.config: dest_domain=google.com port=443 ... round_robin=0 ...
</pre>
</div></div>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
   [Jul 12 02:25:45.987] Server {0x2b54fb7db940} ERROR: [ParentSelection] invalid argument to round_robin directive at line 2
</pre>
</div></div>

Author: Matt Mills
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-489">https://issues.apache.org/jira/browse/TC-489</a>
Found Version: 2.1.0

**Comment by dneuman64** [comment]
@dg4prez can you take a look at fixing this issue and backporting to 2.1?

**Comment by dg4prez** [comment]
https://github.com/apache/incubator-trafficcontrol/pull/1137

**Comment by dneuman64** [comment]
closed by #1137
