### ISSUE TITLE
[TC-393] Traffic Ops API Gateway

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#881]
<p>Build API gateway for Traffic Ops</p>

<p>See: <a href="https://cwiki.apache.org/confluence/display/TC/API+Gateway" class="external-link" rel="nofollow">https://cwiki.apache.org/confluence/display/TC/API+Gateway</a><br/>
See: <a href="https://lists.apache.org/thread.html/e7aa72c73177a25a6a834ebca268c9ac973f547ce77d5331e7f84ee0@%3Cdev.trafficcontrol.apache.org%3E" class="external-link" rel="nofollow">https://lists.apache.org/thread.html/e7aa72c73177a25a6a834ebca268c9ac973f547ce77d5331e7f84ee0@%3Cdev.trafficcontrol.apache.org%3E</a><br/>
See <a href="https://github.com/apache/incubator-trafficcontrol/pull/567" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/pull/567</a></p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-393">https://issues.apache.org/jira/browse/TC-393</a>
Found Version: 2.1.0

**Comment by dewrich** [comment]
The Vampire Proxy Rewrite effort is negating the need (currently) for nginx.  Please see: https://lists.apache.org/thread.html/a226787388bbc8ddd861499b1eec23d878a9ead4c336d3d707ac436e@%3Cdev.trafficcontrol.apache.org%3E
