### ISSUE TITLE
[TC-287] Add support for per-Delivery Service routing/name

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#886]
<p>A default routing name/entry point should be added as a profile parameter, and this parameter should be used by default as the value of the "routing name" or "entry point" on the delivery service in the CRConfig. This value should be overridable on a per-delivery service level, which means that the delivery service UIs should be enhanced to provide this capability and to display the default value.</p>

<p>Once above is implemented, consume the new delivery service parameter and configure accordingly within Traffic Router.</p>

<p>From: <br/>
<a href="https://github.com/Comcast/traffic_control/issues/61" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/61</a><br/>
<a href="https://github.com/Comcast/traffic_control/issues/62" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/62</a></p>

Author: Eric Friedrich
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-287">https://issues.apache.org/jira/browse/TC-287</a>

**Comment by rawlinp** [comment]
This can be closed - implemented in #865
