### ISSUE TITLE
[TC-538] Traffic Stats should be able to poll over IPv6 if IPv4 is not available

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#893]
<p>Currently if you have TM that has A and AAAA records, but only AAAA is available, TS will fail because it tries to use the IPv4 address only.  TS should be smart enough to use the AAAA record if it is available.</p>

Author: David Neuman
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-538">https://issues.apache.org/jira/browse/TC-538</a>

**Comment by dneuman64** [comment]
closed by #1323
