### ISSUE TITLE
[TC-510] cannot apply ipv6 on delivery services

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#897]
<p>attempt to change ipv6 flag from ipv4 to ipv6 results in a / unable to update delivery service.</p>

<p>on trafficops, 2.1.0-6566.3980b417.el7 Also receive following error: </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Traffic Ops fatal error occurred <span class="code-keyword">while</span> processing your request. 
Error at line 50 (    %= field('ds.cdn_id')-&gt;select( \@{$cdns} );) 
Global symbol <span class="code-quote">"$cdns"</span> requires explicit <span class="code-keyword">package</span> name at template delivery_service/_form.html.ep line 50. Global symbol <span class="code-quote">"$profiles"</span> requires explicit <span class="code-keyword">package</span> name at template delivery_service/_form.html.ep line 375.</pre>
</div></div>

Author: Sean Aoyagi
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-510">https://issues.apache.org/jira/browse/TC-510</a>
Found Version: 2.1.0

**Comment by hbeatty** [comment]
Changing to 2.2 based on comment in Jira by Dylan Volz on 8/16/17:

> I believe this can be left for 2.2 because updating delivery services with ipv6 works via the api route, exercised via the new traffic portal. I verified this today.

**Comment by mitchell852** [comment]
TO UI will be deprecated shortly in favor of TP so closing this
