### ISSUE TITLE
[TC-494] Clone DS assignments button on Server times out

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#898]
<p>When you try to clone DS assignments in our current production environment, it will never complete the "clone" process, and gets timed out midway through, leaving you with a broken configuration on that server.</p>

Author: Matt Mills
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-494">https://issues.apache.org/jira/browse/TC-494</a>
Found Version: 2.1.0

**Comment by dneuman64** [comment]
I don't believe this will be fixed in 2.1.  Moving to 2.2

**Comment by rob05c** [comment]
Note this is fixed in Traffic Portal, so when the old Traffic Ops UI is deprecated, this will be implicitly fixed. 

(Not that I'm arguing we shouldn't fix it in the meantime; it could be some time before the old UI is deprecated.)
