### ISSUE TITLE
[TC-373] Traffic Stats Has Connection Leak 

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#900]
<p>Happens when TO not response 200 OK to traffic stats:<br/>
<span class="error">&#91;ERROR&#93;</span> 2017-06-08 09:54:40 500 Internal Server Error<span class="error">&#91;500&#93;</span> - Error requesting Traffic Ops <a href="https://coffee-ops-a.coffee.com/api/1.2/stats_summary/create" class="external-link" rel="nofollow">https://coffee-ops-a.coffee.com/api/1.2/stats_summary/create</a></p>

<p>$ sudo netstat -tunp|grep traffic_stats|head <br/>
tcp       32      0 10.63.115.225:39667     10.63.115.224:443       CLOSE_WAIT  795/traffic_stats   <br/>
tcp       32      0 10.63.115.225:50388     10.63.115.224:443       CLOSE_WAIT  795/traffic_stats   <br/>
tcp       32      0 10.63.115.225:46896     10.63.115.224:443       CLOSE_WAIT  795/traffic_stats   <br/>
tcp       32      0 10.63.115.225:38896     10.63.115.224:443       CLOSE_WAIT  795/traffic_stats   <br/>
tcp        1      0 10.63.115.225:53682     10.63.115.224:443       CLOSE_WAIT  795/traffic_stats   <br/>
tcp       32      0 10.63.115.225:42324     10.63.115.224:443       CLOSE_WAIT  795/traffic_stats   <br/>
tcp       32      0 10.63.115.225:39618     10.63.115.224:443       CLOSE_WAIT  795/traffic_stats   <br/>
tcp       32      0 10.63.115.225:36613     10.63.115.224:443       CLOSE_WAIT  795/traffic_stats   <br/>
tcp       32      0 10.63.115.225:51851     10.63.115.224:443       CLOSE_WAIT  795/traffic_stats   <br/>
tcp       32      0 10.63.115.225:52842     10.63.115.224:443       CLOSE_WAIT  795/traffic_stats </p>

Author: Zhilin Huang
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-373">https://issues.apache.org/jira/browse/TC-373</a>

**Comment by dneuman64** [comment]
I do not believe this will be included in 2.1.  Moving to 2.2.

**Comment by dneuman64** [comment]
#660 was merged which fixes this issue.  Closing
