### ISSUE TITLE
[TC-377] Default profiles for EDGE and MID are missing after initial install

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#901]
<p>I suggest we don't add these to the seeds, but create a "profile exchange" that people can dl the right profile from. </p>

<p>I'll take a first stab at this.</p>

Author: Jan van Doorn
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-377">https://issues.apache.org/jira/browse/TC-377</a>

**Comment by dneuman64** [comment]
@limited default profiles have been provided on our website under downloads. http://trafficcontrol.apache.org/downloads/profiles/2.0.x/default/

**Comment by dneuman64** [comment]
Closing, we are providing links above.
