### ISSUE TITLE
[TC-327] ConfigFiles.pm detects blank as not null and tries to gen files GH #1090

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#906]
<p>ConfigFiles.pm will read a blank in the database as a file that needs creation or action upon. Some defensive code should detect this issue and either treat it as a null or pitch an error with some troubleshooting steps to fix the issue.</p>

<p><a href="https://github.com/Comcast/traffic_control/issues/1090" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1090</a></p>

Author: Dewayne Richardson
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-327">https://issues.apache.org/jira/browse/TC-327</a>

**Comment by dneuman64** [comment]
This is a very old issue so I am closing.  If this is still an issue please re-open.
