### ISSUE TITLE
[TC-317] ORT syncds bug - Parent holds up child running syncds if TO has multiple CDNs

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#908]
<p>Based on: <a href="https://github.com/Comcast/traffic_control/issues/1380" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1380</a></p>

<p>By: jpappa200<br/>
A parent from a different CDN can hold up a child from running syncds if Traffic Ops has multiple CDN's configured.</p>

<p>https://&lt;to_host&gt;/update/ looks at all parents associated with the cache group and doesn't check which CDN it's associated with.</p>

<p>Comment by jeffmart:<br/>
Is this hold up indefinite?<br/>
or<br/>
does syncds complete on the child after all parents for all CDNs in that cache group are updated?<br/>
I am assuming <a href="https://github.com/Comcast/traffic_control/pull/2" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/pull/2</a> but want to make sure</p>

<p>knutsel :<br/>
so we have a issue somewhere to take regex_revalidate out of the ort/syncds distribution mechanism, and scp (or ansible dist) it directly on update; this would remove the "mids have to complete ort syncds before edges" requirement, and things should get a lot better when we do that...</p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-317">https://issues.apache.org/jira/browse/TC-317</a>

**Comment by dneuman64** [comment]
@dg4prez do you know if this is still an issue?  I don't believe it is.  I am moving to 2.2 but if this is not an issue we should close it.

**Comment by dg4prez** [comment]
Looking at both the go version of the API and the legacy UI code (both of which are supported by ORT) it looks like this issue was fixed quite some time ago.
