### ISSUE TITLE
[TC-301] creating https delivery service and not setting to active still looks for cert. Github Issue #1086

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#909]
<p>Original GH issue <a href="https://github.com/Comcast/traffic_control/issues/1086" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1086</a></p>

<p>Que'ed and snapshotted - delivery service was not set to active. On syncds it err's looking for DS cert.<br/>
ERROR Received error code 400 for <a href="https://trafficops/api/1.1/deliveryservices/hostname/deliveryservicename/sslkeys.json" class="external-link" rel="nofollow">https://trafficops/api/1.1/deliveryservices/hostname/deliveryservicename/sslkeys.json</a> from Traffic Ops!<br/>
FATAL SSL URL: <a href="https://trafficops/api/1.1/deliveryservices/hostname/deliveryservicename/sslkeys.json" class="external-link" rel="nofollow">https://trafficops/api/1.1/deliveryservices/hostname/deliveryservicename/sslkeys.json</a> returned 400. Exiting.</p>

<p>Just generating a ssl key and error goes away.<br/>
Copying /tmp/ort/123/trafficserver/config_trops deliveryservicename .cer to /opt/trafficserver/etc/trafficserver/ssl//deliveryservicename_cert.cer<br/>
ERROR Copying /tmp/ort/123/trafficserver/config_trops/deliveryservicename.key to /opt/trafficserver/etc/trafficserver/ssl//deliveryservicename.key</p>

Author: Dewayne Richardson
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-301">https://issues.apache.org/jira/browse/TC-301</a>

**Comment by dneuman64** [comment]
If a DS is not set to active, it will not be included in the CrConfig and therefore TR should not poll for the certs.  I am closing this as I don't believe this is a code issue.  Please re-open if I am incorrect.
