### ISSUE TITLE
[TC-169] TR download the RGB file continuously when the same RGB file on server 

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#912]
<p>If the RGB file on server is: <br/>
1. completely the same with the RGB file on TR<br/>
2. last modified time is later than the RGB file on TR<br/>
TR will download the RGB file from server at every polling interval. </p>

<p>Expected behavior is that TR should not download the RGB file any longer when the RGB file on server has been downloaded to TR and it was unmodified since then.</p>

Author: Zhilin Huang
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-169">https://issues.apache.org/jira/browse/TC-169</a>
Found Version: 2.1.0

**Comment by dneuman64** [comment]
@limited @PeterRyder Can you please determine if this should be included in 2.1.  If not can you move to 2.2.

**Comment by dneuman64** [comment]
PR 315 has been merged into master...Closing this issue.
