### ISSUE TITLE
[TC-116] remap.config order is different on master (postgres) than it is on 1.8.

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#915]
None

Author: Jan van Doorn
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-116">https://issues.apache.org/jira/browse/TC-116</a>
Found Version: 2.1.0

**Comment by knutsel** [comment]
Not relevant anymore, 2.0 has been released, and this is an issue w 1.8->2.0 migration...
