### ISSUE TITLE
[TC-192] Java TM and Go TM get build with exact same RPM Name

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#917]
<p>When building Traffic Control, goTM and javaTM get build with the exact same rpm name.  This means that if you are building all projects you only get one TM RPM and its whichever one built last.  The names should be updated so that they are not the same.</p>

Author: David Neuman
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-192">https://issues.apache.org/jira/browse/TC-192</a>
Found Version: 2.1.0

**Comment by dneuman64** [comment]
moving to 2.2.0.  There is a proposal to remove java TM which will solve this issue.

**Comment by rob05c** [comment]
@limited Java TM is now deprecated, has been moved to `traffic_monitor_java`, and shouldn't ordinarily be built for a 2.2 Traffic Control. Can this be resolved?

**Comment by dneuman64** [comment]
Resolving since Java TM has been moved to a new directory.
