### ISSUE TITLE
[TC-525] Cannot snapshot CrConfig when no mid server exists

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#918]
<p>Traffic Control works well with no MID servers. The edge server can just work against the origin.<br/>
However, if no "MID" server exists, snapshot cr-config fails.</p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-525">https://issues.apache.org/jira/browse/TC-525</a>

**Comment by dg4prez** [comment]
https://github.com/apache/incubator-trafficcontrol/pull/1249

**Comment by dneuman64** [comment]
#1249 is merged which fixes this.  I will teach @dg4prez how to update his PRs to auto-close these!
