### ISSUE TITLE
[TC-501] TPv2 installation - better defaults are required

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#924]
<p>After basic install of traffic-portal based on the documentation, traffic portal failed to launch. this is due to relative pathes to the logs and static files appear in the default configuration.<br/>
Note that the working directory of the server is "/"</p>

<p>First, the log path (./server/log) does not exists. A possible fix is to change the dir to /opt/traffic_portal/server/log and create the log dir if needed. </p>

<p>Second. the files static path should be set to "opt/traffic_portal/public"</p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-501">https://issues.apache.org/jira/browse/TC-501</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
Following the comments found in config.js will correct this problem.

https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_portal/conf/config.js
