### ISSUE TITLE
[TC-445] Traffic Ops API Rewrite: Implement /api/1.2/servers

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#926]
<p>Implement the second TO Golang endpoint </p>

Author: Dewayne Richardson
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-445">https://issues.apache.org/jira/browse/TC-445</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
i think this was already done by @DylanVolz so i'm closing
