### ISSUE TITLE
[TC-184] Tenant Hierarchy Creation

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#931]
<p>Design under discussion here: <a href="https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=68715910" class="external-link" rel="nofollow">https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=68715910</a></p>

<p>The requirements below are seed requirements and final design guidance should defer to the evolving wiki page discussion referenced above.</p>

<p>Overview<br/>
The goal of this system is to create a hierarchical tenancy system which is very simple to understand and administer and is highly expandable so that large organizations with many subsidiaries have the flexibility to create child-tenants to their liking.  </p>

<p>General Seed Requirements<br/>
1. Provide a structure to create a hierarchy of Tenants where each Tenant has a single parent-Tenant and can have multiple child-Tenants<br/>
2. Provide the ability to group multiple Delivery Services, Users, and child- Tenants under each Tenant<br/>
3. Provide the ability to create at least 10 child-Tenant layers within the system<br/>
4. Make it easy to assign a User to a single Tenant so that they inherit their permissions to all child-Tenants and Delivery Services. <br/>
5. Adding child-Tenants or Delivery Services anywhere in an existing tenant hierarchy does not require re-assigning users.  Users inherit pre-defined permissions to new tenants and services added below their assigned layer in the tenancy tree.<br/>
6. Allow Users  to be assigned multiple Tenants, each with different Roles.  While a user would inherit their access to all services and child Tenants below them, they may need more restrictive access further up the Tenant hierarchy or they may want different access to another branch of the tenant tree.</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-184">https://issues.apache.org/jira/browse/TC-184</a>

**Comment by ryandurfey** [comment]
@mitchell852 This can be closed.

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina
@mitchell852 per Ryan's comment, you can close this.
