### ISSUE TITLE
[TC-482] Filtered UI View Persistence and Linking 

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#932]
<p>When doing a large number of edits on users, tenants, or services, I generally filter the list down to view a certain set.  However, when I go to edit any individual user, tenant, or service I lose my filtered view and have to rebuild it after each edit which slows down the process and adds clicks.</p>

<p>Make it so we can open an edit screen in a new window and so that the filter persists in the existing window.  It would be great if the filter could be a part of the URL so you could link directly to a filtered view over time.</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-482">https://issues.apache.org/jira/browse/TC-482</a>

**Comment by mitchell852** [comment]
filters are now retained
