### ISSUE TITLE
[TC-26] Prepare Docker Environment for Traffic Portal

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#955]
<p>Prepare Docker Environment for Traffic Portal</p>

Author: Burak SARP
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-26">https://issues.apache.org/jira/browse/TC-26</a>
Found Version: 1.8.0

**Comment by dneuman64** [comment]
Moving this to the 2.2.0 release as it won't be in 2.1

**Comment by mitchell852** [comment]
not sure what this means. closing.
