### ISSUE TITLE
[TC-217] CRUD Tenant - Self-service

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#969]
<p>Allow users to CRUD sub tenants below their tenant level or below any sub-tenant level they choose. Default would be directly below the current tenant value.</p>

Author: Ashish Timilsina
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-217">https://issues.apache.org/jira/browse/TC-217</a>

**Comment by mitchell852** [comment]
duplicate of #1265
