### ISSUE TITLE
[TC-218] CRUD Users - Self-Service

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#970]
<p>Allow customer (admin roles only) to CRUD users.</p>

<p>1. Creator gets to choose tenant assignment based on any available tenant to the user, default will be for same tenant as the creator.<br/>
2. Creator can sets role for user, default is read only.</p>

Author: Ashish Timilsina
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-218">https://issues.apache.org/jira/browse/TC-218</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
duplicate of #1267
