### ISSUE TITLE
[TC-219] CRUD Delivery Service - Self Service

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#971]
<p>Allow customers to CRUD delivery services via the API and Portal accessing all available features and configurations.</p>

Author: Ashish Timilsina
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-219">https://issues.apache.org/jira/browse/TC-219</a>

**Comment by mitchell852** [comment]
duplicate of #1254
