### ISSUE TITLE
[TC-113] Add support for ATS 6.x config file format

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#977]
<p>Specifically parent.config... But others also? cacheurl plugin?</p>

Author: Jan van Doorn
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-113">https://issues.apache.org/jira/browse/TC-113</a>

**Comment by smalenfant** [comment]
@knutsel I'm assuming that's fixed in 2.1/master since 6.x is being used today. Can we close this?
