### ISSUE TITLE
[TC-353] Can't use CNAME hostname with "ccr" prefix

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#990]
<p>If you put a HOST_REGEX of "ccr.example.kabletown.net", it will expand to the server hostname like "edge01.example.kabletown.net". This makes the remap.config to have the wrong hostname. This might not affect anything but it should be changed to something unrelated to a specific prefix.</p>

<p>The code ConfigFile.pm is causing the current behavior :</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
				my $hname = $ds_type =~ /^DNS/ ? <span class="code-quote">"edge"</span> : <span class="code-quote">"ccr"</span>;
				my $portstr = "";
...
	$map_from =~ s/ccr/$host_name/;
</pre>
</div></div>

Author: Steve Malenfant
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-353">https://issues.apache.org/jira/browse/TC-353</a>
Found Version: 2.1.0

**Comment by smalenfant** [comment]
@hbeatty This is not required for 2.1. Removing milestone.

**Comment by mitchell852** [comment]
@rawlinp - any thoughts on this guy?

**Comment by rawlinp** [comment]
I believe `"ccr"` in this context is basically just used as a placeholder for generating the lines in `remap.config`, where `ccr` gets replaced with the cache's short hostname. We might be able to just change that placeholder to a random string that couldn't possibly be a valid hostname.

**Comment by smalenfant** [comment]
Is it OK if I use `__http__` instead of `ccr` ?

**Comment by rawlinp** [comment]
`__http__` seems reasonable to me.
