### ISSUE TITLE
[TC-515] Traffic Portal - Show human readable protocol on DS page

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#993]
<p>In the TO UI, the delivery service protocol is converted from an int (0,1,2) to a human readable string (http, https, http and https, etc).  The new TO portal just shows the int but it should show the human readable string.</p>

Author: David Neuman
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-515">https://issues.apache.org/jira/browse/TC-515</a>
Found Version: 2.1.0

**Comment by hbeatty** [comment]
fixed in 2.2.

@mitchell852 I'm going to close this "minor" issue since it is fixed in 2.2 and not going to be backported to 2.1.
