### ISSUE TITLE
[TC-500] Creating/Updating a Delivery Service via API has length constraint on displayName of 48, but no such constraint in UI code

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#994]
<p>Creating/Updating a Delivery Service via API code has length constraint on `displayName` of 48, but there is no such constraint in the UI code so any user can update the value to more than 48 characters.  The Database field is Text which is described as "variable unlimited length" in the Postgres documentation.  However, the value may be limited by the GUI field if such a constraint exists.</p>

<p>NOTE:  The GET methods for /api/1.2/deliveryservices does not check the length on the `displayName` field, so, it will return whatever is in the database for `displayName`.</p>

<p>Work Around: Upon getting the Delivery Service information from the API, in order to update/create the Delivery Service via the API you will need to limit the number of characters in the `displayName` to 48.</p>

<p>NOTE: Other versions of Traffic Ops may be affected.</p>

Author: Robert Scrimo
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-500">https://issues.apache.org/jira/browse/TC-500</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
the maxlength of 48 is enforced in the UI and the API already. Maybe the code was updated after this issue was created.
