### ISSUE TITLE
[TC-472] traffic_ops/experimental - failure to assign servers to new Delivery Service

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#997]
<p>While using the new UI, I was unable to assign servers to a newly-created DS. After submitting the change, no servers were linked. No error apparent when submitting. Tried multiple times with same results.</p>

<p>Browser: chrome 58.0.3029.110</p>

Author: Jason Tucker
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-472">https://issues.apache.org/jira/browse/TC-472</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
this is because of a discrepancy between the TP and TP versions
